language: node_js
node_js:
  - "8.9.1"
cache:
  directories:
    - "node_modules"
branches:
  only:
  - development
  - master
before_install:
  - npm install -g nodemon
  - npm install -g ts-node
  - npm install -g tslint
before_script:
  - npm run lint
  - npm run build
after_success:
  - npm run codecov